name: flutter_map_drawing_tools_example
description: Demonstrates how to use the flutter_map_drawing_tools plugin.
publish_to: 'none' # Remove this line if you intent to publish the example app

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map_drawing_tools:
    path: ../ # Depend on the local plugin package

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
