name: flutter_map_drawing_tools
description: A Flutter plugin for interactive drawing, editing, and GeoJSON import/export functionalities on flutter_map.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.1.0
  flutter_map_line_editor: ^1.0.1
  flutter_map_dragmarker: ^7.0.1
  flutter_map_geojson: ^1.1.0
  latlong2: ^0.9.0
  geopoint3: ^1.1.1
  uuid: ^4.3.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_map_drawing_tools # You might want to adjust this package name
        pluginClass: FlutterMapDrawingToolsPlugin
        dartPluginClass: FlutterMapDrawingToolsPlugin
      ios:
        pluginClass: FlutterMapDrawingToolsPlugin
        dartPluginClass: FlutterMapDrawingToolsPlugin
      linux:
        pluginClass: FlutterMapDrawingToolsPlugin
        dartPluginClass: FlutterMapDrawingToolsPlugin
      macos:
        pluginClass: FlutterMapDrawingToolsPlugin
        dartPluginClass: FlutterMapDrawingToolsPlugin
      windows:
        pluginClass: FlutterMapDrawingToolsPlugin
        dartPluginClass: FlutterMapDrawingToolsPlugin
      web:
        pluginClass: FlutterMapDrawingToolsWeb
        fileName: flutter_map_drawing_tools_web.dart
